# File: autojob/src/preprocessing/acronyms.py

acronym_list = {
    "ADA": "American Disabilities Act",
    "AI": "Artificial Intelligence",
    "API": "Application Programming Interface",
    "AR": "Augmented Reality",
    "AWS": "Amazon Web Services",
    "Azure": "Microsoft Azure",
    "B2B": "Business-to-Business",
    "B2C": "Business-to-Consumer",
    "BAU": "Business As Usual",
    "BDC": "Business Development Bank of Canada",
    "BI": "Business Intelligence",
    "BIM": "Building Information Modeling",
    "BLS": "Bureau of Labor Statistics",
    "BSS": "Business support systems",
    "C2C": "Consumer-to-Consumer",
    "CAD": "Computer-Aided Design",
    "CAGR": "Compound Annual Growth Rate",
    "CAPM": "Capital Asset Pricing Model",
    "CBSA": "Canada Border Services Agency",
    "CD": "Continuous Deployment",
    "CEO": "Chief Executive Officer",
    "CFO": "Chief Financial Officer",
    "CI": "Continuous Integration",
    "CI/CD": "Continuous Integration/Continuous Deployment",
    "CIM": "Computer Integrated Manufacturing",
    "CIO": "Chief Information Officer",
    "CMHC": "Canada Mortgage and Housing Corporation",
    "CMO": "Chief Marketing Officer",
    "CMS": "Content Management System",
    "COB": "Close of Business",
    "COO": "Chief Operating Officer",
    "CPG": "Consumer Packaged Goods",
    "CPPIB": "Canada Pension Plan Investment Board",
    "CRM": "Customer Relationship Management",
    "CRS": "Central Reservation System",
    "CRTC": "Canadian Radio-television and Telecommunications Commission",
    "CSI": "Crime Scene Investigation",
    "CSIS": "Canadian Security Intelligence Service",
    "CSM": "Certified Scrum Master",
    "CSS": "Cascading Style Sheets",
    "CTA": "Call to Action",
    "CTC": "Cost to Company",
    "CTO": "Chief Technology Officer",
    "CV": "Curriculum Vitae",
    "DFO": "Department of Fisheries and Oceans Canada",
    "DNS": "Domain Name System",
    "DevOps": "Development Operations",
    "ECCC": "Environment and Climate Change Canada",
    "EHR": "Electronic Health Records",
    "EKG": "Electrocardiography",
    "EMR": "Electronic Medical Records",
    "EOB": "End of Business",
    "EOY": "End of Year",
    "ERP": "Enterprise Resource Planning",
    "ESDC": "Employment and Social Development Canada",
    "ESL": "English as a Second Language",
    "ETA": "Estimated Time of Arrival",
    "ETL": "Extract, Transform, Load",
    "EOD": "End of Day",
    "EOM": "End of Month",
    "FCAC": "Financial Consumer Agency of Canada",
    "FTP": "File Transfer Protocol",
    "FYI": "For Your Information",
    "GCP": "Good Clinical Practice",
    "GIS": "Geographic Information System",
    "GLP": "Good Laboratory Practice",
    "GMP": "Good Manufacturing Practice",
    "GPP": "Good Production Practice",
    "GRP": "Good Regulatory Practice",
    "HCM": "Human Capital Management",
    "HPLC": "High-Performance Liquid Chromatography",
    "HR": "Human Resources",
    "HRIS": "Human Resources Information System",
    "HTML": "Hypertext Markup Language",
    "HTTP": "Hypertext Transfer Protocol",
    "HTTPS": "Hypertext Transfer Protocol Secure",
    "I-9": "Employment Eligibility Verification Form",
    "IBM": "International Business Machines",
    "IC": "Independent Contractor",
    "IFRS": "International Financial Reporting Standards (Adopted by Canadian businesses)",
    "ILO": "International Labour Organization",
    "IoT": "Internet of Things",
    "IRCC": "Immigration, Refugees and Citizenship Canada",
    "JD": "Job Description",
    "JIT": "Just-In-Time",
    "JS": "JavaScript",
    "JSON": "JavaScript Object Notation",
    "KPI": "Key Performance Indicators",
    "KRA": "Key Result Area",
    "KSA": "Knowledge, Skills, Abilities",
    "L&D": "Learning and Development",
    "LEED": "Leadership in Energy & Environmental Design",
    "LMS": "Learning Management System",
    "M&A": "Mergers and Acquisitions",
    "MIS": "Management Information System",
    "ML": "Machine Learning",
    "MoM": "Minutes of Meeting",
    "NDA": "Non-Disclosure Agreement",
    "NGO": "Non-Governmental Organizations (General Term)",
    "NRC": "National Research Council Canada",
    "OH&S": "Occupational Health & Safety",
    "OPEX": "Operational Expenditures",
    "OSFI": "Office of the Superintendent of Financial Institutions",
    "OSS": "Operations Support Systems",
    "P&L": "Profit & Loss",
    "PDU": "Professional Development Unit",
    "PCR": "Polymerase Chain Reaction",
    "PDCA": "Plan-Do-Check-Act",
    "PE": "Private Equity",
    "PESTLE": "Political, Economic, Social, Technological, Legal, Environmental",
    "PIM": "Product Information Management",
    "PLM": "Product Lifecycle Management",
    "PM": "Project Manager",
    "POC": "Proof of Concept",
    "PSPC": "Public Services and Procurement Canada",
    "PTO": "Paid Time Off",
    "QoL": "Quality of Life",
    "QA": "Quality Assurance",
    "QC": "Quality Control",
    "R&D": "Research and Development",
    "RCMP": "Royal Canadian Mounted Police",
    "REST": "Representational State Transfer",
    "RFP": "Request for Proposal",
    "ROA": "Return on Assets",
    "ROE": "Return on Equity",
    "ROI": "Return on Investment",
    "RTO": "Recovery Time Objective",
    "SAP": "System Application Products",
    "SDK": "Software Development Kit",
    "SDLC": "Software Development Life Cycle",
    "SEO": "Search Engine Optimization",
    "SLA": "Service Level Agreement",
    "SME": "Subject Matter Expert",
    "SOAP": "Simple Object Access Protocol",
    "SOPs": "Standard Operating Procedures",
    "SPC": "Statistical Process Control",
    "SQL": "Structured Query Language",
    "SSH": "Secure Shell",
    "SWOT": "Strengths, Weaknesses, Opportunities, Threats",
    "TAT": "Turnaround Time",
    "TBS": "Treasury Board of Canada Secretariat",
    "TCO": "Total Cost of Ownership",
    "TDD": "Test-Driven Development",
    "TNA": "Training Needs Analysis",
    "TPM": "Total Productive Maintenance",
    "TQM": "Total Quality Management",
    "UI": "User Interface",
    "UX": "User Experience",
    "VPN": "Virtual Private Network",
    "VR": "Virtual Reality",
    "VoIP": "Voice over Internet Protocol",
    "WFO": "Workforce Optimization",
    "WFH": "Work From Home",
    "WIP": "Work in Progress",
    "WO": "Work Order",
    "XML": "eXtensible Markup Language",
    "YTD": "Year to Date"
}
